Blogging/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import (
        LoginView, LogoutView, PasswordResetView, PasswordResetDoneView, 
        PasswordResetConfirmView, PasswordResetCompleteView, 
    )
from user import views as u_views
from django.conf import settings
from django.conf.urls.static import static




urlpatterns = [
    path('admin/', admin.site.urls),
    
    # app's urls
    path('', u_views.index,name = 'index'),
    path('user/', include('user.urls', namespace = 'user')),
    path('blog/', include('blog.urls', namespace = 'blog')),
    # path('shop/', include('shop.urls', namespace = 'shop')),

    
    # authentication urls
    path('login/', u_views.login,name = 'login'),
    path('logout/', u_views.logout,name = 'logout'),
    path('signup/', u_views.signup,name = 'signup'),

    # for timymce
    path('tinymce/', include('tinymce.urls')),

    
]


# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)



# if settings.DEBUG:
#     urlpatterns += [(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
#             'document_root': settings.MEDIA_ROOT,
#         }),
#         (r'^static/(?P<path>.*)$', 'django.views.static.serve', {
#             'document_root': settings.STATIC_ROOT,
#         })]

blog/urls.py
from django.contrib import admin
from django.urls import path
from .views import *
# from shop import views



app_name = "blog"

urlpatterns = [
    path('', blog_create,name = 'create'),
    # blog urls
    path('list', blog_list,name = 'list'),
    path('create', blog_create,name = 'create'),
    path('detail/<slug>', blog_detail,name = 'detail'),
    path('for-deletion', blog_for_deletion,name = 'to-delete-blog'),
    path('update/<slug>', BlogUpdateView.as_view(),name = 'update'),
    path('delete-blog/<slug>', blog_delete,name = 'blog-delete'),
    
    # category urls
    path('category/<slug>', blog_by_category,name = 'category-blog'),
    path('create-category', category_create,name = 'create-category'),
    path('category-delte/<slug>', category_delete,name = 'category-delete'),
    path('category-list', category_list,name = 'category-list'),
]

blog/models.py
from django.db import models
from datetime import datetime
from django.db.models.signals import post_save, pre_save, post_delete, pre_delete
from django.utils.text import slugify   
from user.models import User
from guardian.shortcuts import assign_perm
from tinymce.models import HTMLField


class PostQuerySet(models.QuerySet):
    def sorted(self):
        return self.order_by('-created_at')


    def category(self, cat):
        
        qsnew = cat.blogs.all()
        return qsnew




class PostManager(models.Manager):
    def sorted(self):
        return self.get_queryset().sorted()
        

    def get_queryset(self):
        return PostQuerySet(model=self.model, using=self._db)




class BlogCustomModel(models.Manager):
    pass

    def category(self, cat):
        return self.get_queryset().category(cat)


    def get_queryset(self):
        return PostQuerySet(model=self.model, using=self._db)



class Category(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField(unique=True)
    def __str__(self):
        return self.name

class Blog(models.Model):
    title = models.CharField(max_length = 40)
    body = HTMLField(max_length = 800, blank = True, null = True)
    author = models.ForeignKey(User, related_name = "blogs", on_delete=models.CASCADE, blank = True, null=True)
    created_on = models.DateTimeField(default = datetime.now())
    img = models.ImageField(upload_to = "blog/", blank = True, null = True)

    category = models.ManyToManyField(Category, related_name = "blogs", blank = True, null = True)

    last_updated = models.DateTimeField(auto_now = True, blank = True, null = True)

    objects = BlogCustomModel()

    deleted = models.BooleanField(default = False)

    published = models.BooleanField(default = False)

    slug = models.SlugField(unique=True)


    class Meta:
        permissions = [("can_change_blog", "can change this blog")]


    def __str__(self):
        return self.title + ", by: " + str(self.author)




def post_blog_created_signal(sender, instance, created, **kwargs):
    if created:
        instance.edited = None
        assign_perm(
            "blog.can_change_blog", 
            instance.author,
            instance
        )
        assign_perm(
            "blog.change_blog", 
            instance.author,
            instance
        )
        


 


def create_slug(instance, new_slug = None):
    slug = slugify(instance.title)
    if new_slug is not None:
        slug = new_slug
    qs = Blog.objects.filter(slug = slug)
    exists = qs.exists()
    if exists:
        new_slug = "%s-%s"%(slug, qs.first().id)
        return create_slug(instance, new_slug = new_slug)
    return slug



def create_slug_category(instance, new_slug = None):
    slug = slugify(instance.name)
    if new_slug is not None:
        slug = new_slug
    qs = Blog.objects.filter(slug = slug)
    exists = qs.exists()
    if exists:
        new_slug = "%s-%s"%(slug, qs.first().id)
        return create_slug(instance, new_slug = new_slug)
    return slug


def pre_blog_created_signal(sender, instance, **kwargs):
    if not instance.slug:
        instance.slug = create_slug(instance)
    



def pre_category_created_signal(sender, instance, **kwargs):
    
    if not instance.slug:
        instance.slug = create_slug_category(instance)
    





post_save.connect(post_blog_created_signal, sender = Blog)
pre_save.connect(pre_blog_created_signal, sender = Blog)
pre_save.connect(pre_category_created_signal, sender = Category)

blog/forms.py
from django import forms
from .models import Blog, Category
from user.models import User
from datetime import datetime
from django.core.mail import send_mail
from tinymce.widgets import TinyMCE
from django.shortcuts import reverse

# from django.contrib.flatpages.models import FlatPage



class BlogCreationForm(forms.ModelForm):

    body = forms.CharField(widget=TinyMCE(attrs={'cols': 80, 'rows': 30}, mce_attrs={}))


    class Meta:
        model = Blog
        fields = ("title", 'body', 'img','category', "deleted", "published")

    
    def save(self, commit=True, **kwargs):
        m = super(BlogCreationForm, self).save()

        if "deleted" in self.changed_data and self.cleaned_data["deleted"]:

            # send mail
            print("Notify the admin for deletion")
            mail_result = send_mail(
            subject = f'Deletion has been requested for blog: {str(m)}',
            message = f'''Author {m.author} has requested deletion of the blog:
                {m.title}
                {m.body}
            ''',
            from_email = 'satansin2001@gmail.com',
            recipient_list = ['stmsng2001@gmail.com'],
            fail_silently=False,
            )
        return m
    

    def __init__(self, *args, **kwargs):
        # breakpoint()    
        user = None
        if "user" in kwargs:
            user = kwargs.pop('user')

        super(BlogCreationForm, self).__init__(*args, **kwargs)
        self.fields['category'].widget = forms.CheckboxSelectMultiple()
        self.fields['category'].queryset = Category.objects.all()
        
        blog = self.instance
        if user:
            blog.author = user
        



class CategoryCreationForm(forms.ModelForm):


    class Meta:
        model = Category
        fields = ("name",)

    
    def saveasdasd(self, commit=True, **kwargs):
        m = super(BlogCreationForm, self).save()
        if "deleted" in self.changed_data and self.cleaned_data["deleted"]:

            # send mail
            print("Notify the admin for deletion")
            mail_result = send_mail(
            subject = f'Deletion has been requested for blog: {str(m)}',
            message = f'''Author {m.author} has requested deletion of the blog:
                {m.title}
                {m.body}
            ''',
            from_email = 'satansin2001@gmail.com',
            recipient_list = ['stmsng2001@gmail.com'],
            fail_silently=False,
            )
        return m

blog/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.http import HttpResponse
from django.shortcuts import redirect, reverse

from .forms import BlogCreationForm, CategoryCreationForm
from .models import Blog, Category
from .decorators import custom_login_required, allowed_users, group_required
from django.contrib.auth.decorators import permission_required, login_required
from guardian.shortcuts import get_objects_for_user
from .permissions import (IsBlogAuthor, 
            SameUserOnlyMixin,
            is_author_decorator,
            CheckAuthorMixin
)
from django.views.generic import UpdateView 
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.utils.decorators import method_decorator

# Create your views here.


# @custom_login_required
# @allowed_users(allowed_users = ['author'])
# @permission_required('blog.add_blog')
# @group_required('author')
@permission_required({("blog.view_blog"), ("blog.can_add_new_blog")})
def blog_create(request):
    msg = ''
    # if not request.user.verified:
    #     msg = "you are not verified as an author"
    
    
    if request.method == 'POST':
        form = BlogCreationForm(request.POST,request.FILES or None, user = request.user)

        if form.is_valid():
            # print(request.user.email, request.user.id)
            bl = form.save()
            # bl.author = request.user
            # bl.save()
            # print(form.cleaned_data)
            # title = form.cleaned_data['title']
            # body = form.cleaned_data['body']
            # author = request.user


            # blog = Blog.objects.create(
            #     author = author,
            #     body = body,
            #     title = title
            # )
            # msg = 'Form Submitted.'
            return redirect("blog:list")

        else:
            print(form.errors)
            print('\n\nForm Invalid!!!')

    form = BlogCreationForm(user = request.user)
    context = {"form": form, "msg":msg}
    return render(request, "blog/blog_create.html", context)






# @login_required
# @permission_required("blog.change_blog")
@is_author_decorator
def blog_update(request, slug):

    blog = Blog.objects.get(slug = slug)
    # blogs = get_objects_for_user(request.user, 'blog.can_change_blog', klass = Blog)
    # print(blogs)
    # print(blogs[0])
    # blog = blogs.get(slug=slug)
    print(blog)
    form = BlogCreationForm(instance = blog)
    msg = ''

    # if request.user != blog.author:
    #     return redirect("blog:list")
    
    # form = BlogCreationForm
    if request.method == 'POST':
        form = BlogCreationForm(request.POST, request.FILES or None, instance = blog)

        if form.is_valid():
            form.save()
             

            return redirect("blog:list")

        else:
            print(form.errors)
            print('\n\nForm Invalid!!!')

    context = {"form": form, "msg":msg, "blog":blog}
    return render(request, "blog/blog_create.html", context)






class BlogUpdateView(CheckAuthorMixin, UpdateView):
    template_name = 'blog/blog_create.html'
    form_class = BlogCreationForm


    def get_success_url(self):

        return reverse('blog:list')     


    def get_queryset(self):
        queryset = Blog.objects.all()
        print(queryset)
        return queryset


    def get_context_data(self, **kwargs):
        # prod_id = self.kwargs['pk']
        
        # prod = Item.objects.get(id = prod_id)

        context = super().get_context_data(**kwargs)
        context.update({
            'item':"hue hie hieiashsdknakksdn",
            # "prod":prod.product,
        })
        return context


    def form_valid(self, form):
        prod = form.save(commit=False)
        
        prod.save()
        return super(BlogUpdateView, self).form_valid(form)








@login_required
@permission_required("blog.view_blog")
def blog_detail(request, slug):
    blog = Blog.objects.get(slug=slug)
    return render(request, "blog/blog_detail.html", {"blog":blog})



@login_required
@permission_required("blog.view_blog")
def blog_list(request):

    
    if request.GET.get("q"):
        # print("\n\n\n\n",self.request.GET.get("q"), "get")
        # queryset = queryset.filter(name__icontains = self.request.GET.get("q"))
        # q2 = Product.objects.filter(index__icontains = self.request.GET.get("q"), shop__pk = self.kwargs['pk'])
        # print(q2)
        # print("final qs: ", queryset)
        # queryset = queryset.union(q2)
        blogs = Blog.objects.filter(title__icontains = request.GET.get("q"))
        print(blogs)
        context = {"blogs":blogs}
        context["categories"] = Category.objects.all()
        return render(request, "blog/blog_list.html", context)


    blogs = Blog.objects.filter(published=True)
    # blogs = get_objects_for_user(request.user, 'blog.view_blog', klass = Blog)
    print(blogs)
    context = {"blogs":blogs}
    context["categories"] = Category.objects.all()
    context["drafts"] = Blog.objects.filter(published=False, author=request.user)
    context["del_request"] = Blog.objects.filter(deleted = True).count()
    print(context["drafts"])
    return render(request, "blog/blog_list.html", context)


def blog_by_category(request, slug = None):

    if request.GET.get("q"):
        # print("\n\n\n\n",self.request.GET.get("q"), "get")
        # queryset = queryset.filter(name__icontains = self.request.GET.get("q"))
        # q2 = Product.objects.filter(index__icontains = self.request.GET.get("q"), shop__pk = self.kwargs['pk'])
        # print(q2)
        # print("final qs: ", queryset)
        # queryset = queryset.union(q2)
        blogs = Blog.objects.filter(title__icontains = request.GET.get("q"))
        print(blogs)
        context = {"blogs":blogs}
        context["categories"] = Category.objects.all()
        return render(request, "blog/blog_list.html", context)

    cat = Category.objects.get(slug = slug)
    blogs = Blog.objects.category(cat)
    # blogs = Blog.objects.all()
    # print(blogs)
    context = {"blogs":blogs}
    context["categories"] = Category.objects.all()
    context["cat_label"] = cat.name
    return render(request, "blog/blog_list.html", context)



def blog_for_deletion(request):
    blogs = Blog.objects.filter(deleted = True)
    return render(request, "blog/blog_list.html", {"blogs":blogs, "num_del":len(blogs)})



def blog_delete(request, slug):
    if request.user.is_superuser:
        blog = Blog.objects.get(slug = slug)
        blog.delete()
    return redirect("blog:list")





#---------------- CATEGORY VIEWS ----------------


def category_create(request):
    msg = ''
    if not request.user.is_superuser:
        msg = "you are not verified as a superuser"
    
    
    if request.method == 'POST':
        form = CategoryCreationForm(request.POST)

        if form.is_valid():
            bl = form.save()
            return redirect("blog:list")

        else:
            print(form.errors)
            print('\n\nForm Invalid!!!')

    form = CategoryCreationForm()
    context = {"form": form, "msg":msg}
    return render(request, "blog/category/category_create.html", context)



def category_list(request):


    category = Category.objects.all()
    # print(blogs)
    context = {"categories":category}
    
    return render(request, "blog/category/category_list.html", context)



def category_delete(request, slug):
    if request.user.is_superuser:
        blog = Category.objects.get(slug = slug)
        blog.delete()
    return redirect("blog:list")

blog/templates/blog/blog_create.html
{% extends "base.html" %} {% load tailwind_filters %} {% block content %}
<div class="max-w-lg mx-auto">
  {% if item %}
    {{item}}
  {% endif %}
  
  <form action="" method="POST" enctype = "multipart/form-data">
    {% csrf_token %}
    {{form.media}}
    {{ form|crispy }}
    <button
      class="w-full bg-blue-500 hover:bg-blue-600 px-3 py-1 rounded-md"
      type="submit"
    >
      Submit Blog
    </button>  
  </form>

</div>
{% endblock %}

blog/templates/blog/blog_detail.html
{% extends "base.html" %} {% load tailwind_filters %} {% block content %}
{% load static %}

<div class="container my-24 px-6 mx-auto">

    <!-- Section: Design Block -->
    <section class="mb-32">
      <style>
        @media (min-width: 992px) {
          #cta-img-nml-50 {
            margin-left: 50px;
          }
        }
      </style>
  
      <div class="flex flex-wrap">
        <div class="grow-0 shrink-0 basis-auto w-full lg:w-5/12 mb-12 lg:mb-0">
          <div class="flex lg:py-12">
          </div>
            {% if blog.img == None %}
                <img src="https://cdn.pixabay.com/photo/2015/04/23/22/00/tree-736885__480.jpg" class="w-full rounded-lg shadow-lg"
                id="cta-img-nml-50" style="z-index: 10" alt="" />
                
            {% else %}
                {{blog.img}} asdadads
                <img src="{% static blog.img %}"
                id="cta-img-nml-50" style="z-index: 10" alt="" />
                {% comment %} <img src = "/{{blog.img}}"> {% endcomment %}
            {% endif %}
        </div>
  
        <div class="grow-0 shrink-0 basis-auto w-full lg:w-7/12">
          <div
            class="bg-yellow-500 h-full rounded-lg p-6 lg:pl-12 text-white flex items-center text-center lg:text-left">
            <div class="lg:pl-12">
              <h2 class="text-3xl font-bold mb-6">{{blog.title}}</h2>
              
  
              <div class="flex flex-col md:flex-row md:justify-around xl:justify-start mb-6 mx-auto">
                
                {% for cat in blog.category.all %}
                <a href = "{% url 'blog:category-blog' slug=cat.slug %}">
                <span class="bg-blue-100 text-blue-800 text-sm font-medium mr-2 px-2.5 py-0.5 rounded dark:bg-blue-200 dark:text-blue-800">{{cat}}</span>
            
                </a>
                {% endfor %}

              </div>
  
              <p>
                  {{blog.body|safe}}
              </p>
            </div>
        </div>
        <p class="text-right"><i>edited- </i> {{blog.last_updated}}</p>
        <p class="text-right"><i>created- </i> {{blog.created_on}}</p>
        by- {{blog.author}} 
        <br>
        
        </div>
        </div>
    </div>
    </section>
    <!-- Section: Design Block -->
  
  </div>
  
{% endblock %}

blog/templates/blog/blog_list.html
{% extends "base.html" %} {% load tailwind_filters %} {% block content %}
{% load static %}
<style>
   body {
      font-family: "Segoe UI", Tahoma, Geneva, Verdana, sans-serif;
   }
   * {
      box-sizing: border-box;
   }
   .card {
      color: white;
      float: left;
      width: calc(25% - 20px);
      padding: 10px;
      border-radius: 10px;
      margin: 10px;
      height: 300px;
   }
   .card p {
      font-size: 18px;
   }
   .cardContainer:after {
      content: "";
      display: table;
      clear: both;
   }
   @media screen and (max-width: 600px) {
      .card {
         width: 100%;
      }
   }
</style>
<section>

     {% comment %} the search bar {% endcomment %}

     <br>
     <div class = "mx-auto" style = "width:100%;">
       <form method = "GET">
         <div class="pt-2 relative mx-auto text-gray-600">
         <input class="border-2 border-gray-300 bg-white h-10 px-5 pr-16 rounded-lg text-sm focus:outline-none form-control relative flex-auto min-w-0 block w-full px-3 py-1.5 text-base font-normal text-gray-700 bg-white bg-clip-padding border border-solid border-gray-300 rounded transition ease-in-out m-0 focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none"
           type="text" name="q" placeholder="Search Blogs">
         <button type="submit" class="absolute right-0 top-0 mt-5 mr-4">
           <svg class="text-gray-600 h-4 w-4 fill-current" xmlns="http://www.w3.org/2000/svg"
             xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" id="Capa_1" x="0px" y="0px"
             viewBox="0 0 56.966 56.966" style="enable-background:new 0 0 56.966 56.966;" xml:space="preserve"
             width="512px" height="512px">
             <path
               d="M55.146,51.887L41.588,37.786c3.486-4.144,5.396-9.358,5.396-14.786c0-12.682-10.318-23-23-23s-23,10.318-23,23  s10.318,23,23,23c4.761,0,9.298-1.436,13.177-4.162l13.661,14.208c0.571,0.593,1.339,0.92,2.162,0.92  c0.779,0,1.518-0.297,2.079-0.837C56.255,54.982,56.293,53.08,55.146,51.887z M23.984,6c9.374,0,17,7.626,17,17s-7.626,17-17,17  s-17-7.626-17-17S14.61,6,23.984,6z" />
           </svg>
         </button>
       </div>
         
       </form>
     </div> 
     <br>



<h1> The categories: </h1>
   {% for cat in categories %}
      <a href = "{% url 'blog:category-blog' slug=cat.slug %}">
         <span class="bg-blue-100 text-blue-800 text-sm font-medium mr-2 px-2.5 py-0.5 rounded dark:bg-blue-200 dark:text-blue-800">{{cat}}</span>

      </a>

   {% endfor %}

{% comment %} Delete link if blogs requested for delete {% endcomment %}
   {% if True %}
   <a href = "{% url 'blog:to-delete-blog' %}" class = "text-right">
      <span class="text-right bg-red-100 text-blue-800 text-sm font-medium mr-2 px-2.5 py-0.5 rounded dark:bg-red-200 dark:text-blue-800">Requested for Deletion {{del_request}}</span>

   </a>
   {% else %}
   {% endif %}

{% comment %} Blog list Heading {% endcomment %}
{% if cat_label %}
   <h1> These are all the blogs in {{cat_label}}: </h1>   
{% elif num_del %}
   <h1>{{cat_label}} blogs requested for deletion</h1>   

{% else %}
   <h1> These are all the blogs till now: </h1>
{% endif %}

<div class="container jumbotron-container cardContainer grid">
   <div>
      {% for blog in blogs %}
            <a href = "{% url 'blog:update' slug=blog.slug %}">
               {% if blog.author == request.user %}
                  <div class="card" style="background-color:rgb(15, 229, 22); height:500px" >   
               {% else %}
                  <div class="card" style="background-color:rgb(153, 29, 224); height:500px">
               {% endif %}
            {% if blog.img %}
               <img src = "{% static blog.img %}" style="height:200px; width:400px">
            {% else %}
               <img src = "https://cdn.pixabay.com/photo/2015/04/23/22/00/tree-736885__480.jpg" style="height:200px; width:400px">
            {% endif %}
            <a href = "{% url 'blog:detail' slug=blog.slug %}">
         <h1 class = "text-2xl hover:text-base">{{blog.title}}</h1>
            </a>
         <br>
         <p> {{blog.body|safe|slice:":15" }}...</p>
         <br>
         <p class="text-right">by- {{blog.author}}</p>
         {% if blog.last_updated %}
               <p class="text-right"><i>edited- </i> {{blog.last_updated}}</p>
         {% else %}
               <p class="text-right"><i>created- </i> {{blog.created_on}}</p>
         {% endif %}
         <br>
         
         {% for cat in blog.category.all %}
            <a href = "{% url 'blog:category-blog' slug=cat.slug %}">
               <span class="bg-blue-100 text-blue-800 text-sm font-medium mr-2 px-2.5 py-0.5 rounded dark:bg-blue-200 dark:text-blue-800">{{cat}}</span>
         
            </a>
            {% endfor %}
            {% comment %} the delete button {% endcomment %}
            {% if request.user.is_superuser %}
               <a href = "{% url 'blog:blog-delete' slug=blog.slug %}">
                  <button class = "btn btn-primary btn-blue">Delete
                     {% comment %} <span class="bg-red-100 text-blue-800 text-sm font-medium mr-2 px-2.5 py-0.5 rounded dark:bg-red-200 dark:text-blue-800">Delete</span> {% endcomment %}
                  </button>
               </a>
            
            {% else %}
            {% endif %}
         </div>  
         </a>
         
      {% endfor %}
   </div>

      <br><br>
      <hr/>
      <br>

   {% if drafts %}
   <div style="display:block">
      <h1 style="background:Red;font-weight:Bold; font-size:30px">Your drafts:</h1>
      {% for blog in drafts %}
         <a href = "{% url 'blog:update' slug=blog.slug %}">
         <div class="card" style="background-color:rgb(250, 89, 152); height:500px" >      
         {% if blog.img %}
            <img src = "{% static blog.img %}" style="height:200px; width:400px">
         {% else %}
            <img src = "https://cdn.pixabay.com/photo/2015/04/23/22/00/tree-736885__480.jpg" style="height:200px; width:400px">
         {% endif %}
         <a href = "{% url 'blog:detail' slug=blog.slug %}">
      <h1 class = "text-2xl hover:text-base">{{blog.title}}</h1>
         </a>
      <br>
      <p> {{blog.body|safe|slice:":15" }}...</p>
      <br>
      <p class="text-right">by- {{blog.author}}</p>
      {% if blog.last_updated %}
            <p class="text-right"><i>edited- </i> {{blog.last_updated}}</p>
      {% else %}
            <p class="text-right"><i>created- </i> {{blog.created_on}}</p>
      {% endif %}
      <br>
      
      {% for cat in blog.category.all %}
         <a href = "{% url 'blog:category-blog' slug=cat.slug %}">
            <span class="bg-blue-100 text-blue-800 text-sm font-medium mr-2 px-2.5 py-0.5 rounded dark:bg-blue-200 dark:text-blue-800">{{cat}}</span>
      
      </a>
      {% endfor %}
            {% comment %} the delete button {% endcomment %}
      </a>
      {% endfor %}

   </div>
      {% endif %}


   </div>
{% endblock %}