Blogging/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import (
        LoginView, LogoutView, PasswordResetView, PasswordResetDoneView, 
        PasswordResetConfirmView, PasswordResetCompleteView, 
    )
from user import views as u_views
from django.conf import settings
from django.conf.urls.static import static




urlpatterns = [
    path('admin/', admin.site.urls),
    
    # app's urls
    path('', u_views.index,name = 'index'),
    path('user/', include('user.urls', namespace = 'user')),
    path('blog/', include('blog.urls', namespace = 'blog')),
    # path('shop/', include('shop.urls', namespace = 'shop')),

    
    # authentication urls
    path('login/', u_views.login,name = 'login'),
    path('logout/', u_views.logout,name = 'logout'),
    path('signup/', u_views.signup,name = 'signup'),

    # for timymce
    path('tinymce/', include('tinymce.urls')),

    
]


# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)



# if settings.DEBUG:
#     urlpatterns += [(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
#             'document_root': settings.MEDIA_ROOT,
#         }),
#         (r'^static/(?P<path>.*)$', 'django.views.static.serve', {
#             'document_root': settings.STATIC_ROOT,
#         })]

blog/urls.py
from django.contrib import admin
from django.urls import path
from .views import *
# from shop import views



app_name = "blog"

urlpatterns = [
    path('', blog_create,name = 'create'),
    # blog urls
    path('list', blog_list,name = 'list'),
    path('create', blog_create,name = 'create'),
    path('detail/<slug>', blog_detail,name = 'detail'),
    path('for-deletion', blog_for_deletion,name = 'to-delete-blog'),
    path('update/<slug>', BlogUpdateView.as_view(),name = 'update'),
    path('delete-blog/<slug>', blog_delete,name = 'blog-delete'),
    
    # category urls
    path('category/<slug>', blog_by_category,name = 'category-blog'),
    path('create-category', category_create,name = 'create-category'),
    path('category-delte/<slug>', category_delete,name = 'category-delete'),
    path('category-list', category_list,name = 'category-list'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <script src="https://cdn.tailwindcss.com"></script>

    {% comment %}
    <script src="static//prod_list.js"></script>
    {% endcomment %} {% comment %}
    <script src="https://unpkg.com/flowbite@1.3.4/dist/flowbite.js"></script>

    {% endcomment %}
    <link
      rel="stylesheet"
      href="https://unpkg.com/flowbite@1.3.4/dist/flowbite.min.css"
    />
    <link
      rel="stylesheet"
      href="https://unpkg.com/flowbite@1.3.4/dist/flowbite.min.css"
    />
    <link
      rel="stylesheet"
      href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css"
    />
    <script src="https://unpkg.com/flowbite@1.3.4/dist/flowbite.js"></script>
    <script src="./TW-ELEMENTS-PATH/dist/js/index.min.js"></script>
    <script src="https://cdn.jsdelivr.net/gh/alpinejs/alpine@v2.x.x/dist/alpine.min.js"></script>
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
    />
    <style>
      body {
        /*background-color: rgba(249, 249, 250, 0.795);
         color: White; */
      }
    </style>
    <style>
      body {
        width: 95%;
        align-self: auto;
        align-items: center;
        align-content: center;
        padding-left: 5%;
        background: #e6e3e3;
      }
      .container {
        max-width: 50%;
        border-bottom: 10px;
      }
    </style>
    
    <title>Blogging Project</title>
    {{ form.media }}

  </head>
  <body>
    <div class="container">
      {% include "navbar.html" %} 
      {% block content %} {% endblock content %}
      {% comment %} {% include "footer.html" %} {% endcomment %}
    </div>
  </body>


<script >

{% comment %} 
tinymce.init({
  selector: 'textarea',  // change this value according to your HTML
  plugins: 'link',
  menubar: 'insert',
  toolbar: 'link'
});
   {% endcomment %}

    
tinymce.init({
  selector: 'textarea',
  plugins: 'image code link',
  toolbar: 'undo redo | link image | code | link',
  /* enable title field in the Image dialog*/
  image_title: true,
  /* enable automatic uploads of images represented by blob or data URIs*/
  automatic_uploads: true,
  /*
    URL of our upload handler (for more details check: https://www.tiny.cloud/docs/configure/file-image-upload/#images_upload_url)
    images_upload_url: 'postAcceptor.php',
    here we add custom filepicker only to Image dialog
  */
  file_picker_types: 'image',
  /* and here's our custom image picker*/
  file_picker_callback: function (cb, value, meta) {
    var input = document.createElement('input');
    input.setAttribute('type', 'file');
    input.setAttribute('accept', 'image/*');

    /*
      Note: In modern browsers input[type="file"] is functional without
      even adding it to the DOM, but that might not be the case in some older
      or quirky browsers like IE, so you might want to add it to the DOM
      just in case, and visually hide it. And do not forget do remove it
      once you do not need it anymore.
    */

    input.onchange = function () {
      var file = this.files[0];

      var reader = new FileReader();
      reader.onload = function () {
        /*
          Note: Now we need to register the blob in TinyMCEs image blob
          registry. In the next release this part hopefully won't be
          necessary, as we are looking to handle it internally.
        */
        var id = 'blobid' + (new Date()).getTime();
        var blobCache =  tinymce.activeEditor.editorUpload.blobCache;
        var base64 = reader.result.split(',')[1];
        var blobInfo = blobCache.create(id, file, base64);
        blobCache.add(blobInfo);

        /* call the callback and populate the Title field with the file name */
        cb(blobInfo.blobUri(), { title: file.name });
      };
      reader.readAsDataURL(file);
    };

    input.click();
  },
  content_style: 'body { font-family:Helvetica,Arial,sans-serif; font-size:14px }'
});



</script>



</html>

templates/index.html
{% extends "base.html" %} {% load tailwind_filters %} {% block content %}
<h1>
    Welcome
</h1>
{% endblock %}

templates/navbar.html
<header class="text-gray-600 body-font">
  <div
    class="container mx-auto flex flex-wrap p-5 flex-col md:flex-row items-center"
  >
    <a
      class="flex title-font font-medium items-center text-gray-900 mb-4 md:mb-0"
    >
      <svg
        xmlns="http://www.w3.org/2000/svg"
        fill="none"
        stroke="currentColor"
        stroke-linecap="round"
        stroke-linejoin="round"
        stroke-width="2"
        class="w-10 h-10 text-white p-2 bg-indigo-500 rounded-full"
        viewBox="0 0 24 24"
      >
        <path
          d="M12 2L2 7l10 5 10-5-10-5zM2 17l10 5 10-5M2 12l10 5 10-5"
        ></path>
      </svg>
      <a href="/"><span class="ml-3 text-xl">Blogger</span></a>
    </a>
    <nav
      class="md:ml-auto flex flex-wrap items-center text-base justify-center"
    >
      <a class="mr-5 hover:text-gray-900" href="/admin">Admin</a>
      <a class="mr-5 hover:text-gray-900" href="{%url 'blog:list'%}"
        >Blog List</a
      >
      {% if request.user.is_superuser %}
      <a class="mr-5 hover:text-gray-900" href="{%url 'blog:create-category'%}"
        >Create Category</a
      >
      {% endif %}
      {% if request.user.verified %}
      <a class="mr-5 hover:text-gray-900" href="{%url 'blog:create'%}"
        >Create Blog</a
      >
      {% endif %}

      {% if request.user.is_authenticated %}
      {{ request.user.name }}
      {% comment %} <a href="{% url 'agents:agent_detail' request.user.agent.id %}"
        ></a
      > {% endcomment %}
      <a href="/logout">
        <button
          class="inline-flex items-center bg-gray-100 border-0 py-1 px-3 focus:outline-none hover:bg-gray-200 rounded text-base mt-4 md:mt-0"
        >
          Logout
          <svg
            fill="none"
            stroke="currentColor"
            stroke-linecap="round"
            stroke-linejoin="round"
            stroke-width="2"
            class="w-4 h-4 ml-1"
            viewBox="0 0 24 24"
          >
            <path d="M5 12h14M12 5l7 7-7 7"></path>
          </svg>
        </button>
      </a>
      {% else %}
      <a class="mr-5 hover:text-gray-900" href="/signup">Sign-up</a>
      <a class="mr-5 hover:text-gray-900" href="/login">Login</a>
      {% endif %}
    </nav>
  </div>
</header>